# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
src             = 'src'                   # The source directory
test            = 'tests'                 # The test directory
libs            = ['lib']                 # A list of library directories
solc_version    = '0.8.24'                # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer       = true                    # Enable or disable the solc optimizer
optimizer_runs  = 100
verbosity       = 3                       # The verbosity of tests
gas_limit       = "18446744073709551615"  # Gas limit for tests
via_ir = true
fs_permissions = [{ access = "write", path = "./"}]
evm_version = "cancun"

[profile.staking]
test = {'tests/Staking.t.sol' = ['MasterVaultTest']}
optimizer = false

[profile.production]
optimizer      = true  # Enable or disable the solc optimizer
optimizer_runs = 100  # The number of optimizer runs

[fuzz]
runs = 100

[invariant]
runs           = 10     # The number of calls to make in the invariant tests
depth          = 100    # The number of times to run the invariant tests
call_override  = false  # Override calls
fail_on_revert = true   # Fail the test if the contract reverts

[profile.default.fuzz]
include_storage = false
runs = 10000

[fmt]
line_length = 120
tab_width = 4
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = false

